### ISSUE TITLE
Variable names

### ISSUE THREAD

**Issue by chunzg** [fac21/week8-evgamy#21]
https://github.com/fac21/week8-evgamy/blob/bcf12ba176fa0c72ceb3cf64539a0301de48f6ef/src/HungryFAC.jsx#L7

We assume you were going to use FAC mentor pictures instead of the cats originally, is that why you have variable names like this? If it's gonna stay as cats, perhaps catOne, catTwo etc would be more accessible to people reading your code

**Comment by amykuner** [comment]
muahahahahahaha
